### Mostrar el usuario 2
GET http://localhost:8080/usuario/2

### Mostrar el usuario 10
GET http://localhost:8080/usuario/10

### Mostrar toda la tabla
GET http://localhost:8080/usuario

###
#POST http://localhost:8080/persona
#Content-Type: application/json
#Accept: application/json

#{
#   "personaId": 9,
#   "nombre": "Gabriel",
#   "apellido": "Murillo"
#}

###UPDATE
POST http://localhost:8080/persona
Content-Type: application/json
Accept: application/json

{
   "personaId": 9,
   "nombre": "Gabriel",
   "apellido": "Murillo"

}